#
#services:
#  app:
#    image: python:3.11
#    working_dir: /app
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


#services:
#  app:
#    build: .
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
#
#
#  db:
#    image: postgres:15
#    restart: always
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mydatabase
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:






services:
  mongo:
    image: mongo:8.0.6
    restart: always

    ports:
      - "27017:27017"


  backend:
    build: .
    depends_on:
      - mongo
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://mongo:27017/"
