services:
  mongo:
    image: mongo:8.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo_express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"

  backend:
    build: .
    depends_on:
      - mongo
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/"
